### ISSUE TITLE
Inconsistent table list

### ISSUE THREAD

**Issue by martinjuckes** [ramipaerosols/RAMIP#1]
Hi, I'm configuring our file checker to use RAMIP tables so that the data can be ingested at CEDA.

There is an inconsistency between the table_id list in RAMIP_CV.json and the actual list of files present (there should be a RAMP_xxx.json file for each table_id entry).

Please check that the all the desired tables are present and update the list in RAMP_CV.json to match.

**Comment by ramipaerosols** [comment]
HI Martin,
I've removed the unused tables from the table_id list in RAMIP_CV.json. 
Cheers!
